### PR TITLE
Fix `prefer_unquoted_atoms` (match better)

### LINKED ISSUE #454: Revisit `prefer_unquoted_atoms`
## Bug Description

These are getting flagged, for example:

```
    - Atom "'=='" on line 458 is quoted but quotes are not needed.
    - Atom "'/='" on line 459 is quoted but quotes are not needed.
    - Atom "'=<'" on line 460 is quoted but quotes are not needed.
    - Atom "'<'" on line 461 is quoted but quotes are not needed.
    - Atom "'>='" on line 462 is quoted but quotes are not needed.
    - Atom "'>'" on line 463 is quoted but quotes are not needed.
    - Atom "'=:='" on line 464 is quoted but quotes are not needed.
    - Atom "'=/='" on line 465 is quoted but quotes are not needed.
    - Atom "'='" on line 468 is quoted but quotes are not needed.
    - Atom "'--'" on line 469 is quoted but quotes are not needed.
```

(from `elvis_style`)

## To Reproduce

On the `elvis_core` root folder: `rebar3 escriptize ; _build/default/bin/elvis_core`

## Expected Behavior

Only flag an atom for "quotes are not required" if that's actually the case.

## `rebar3` Logs

Not applicable.

## Additional Context

Not applicable.

### PR DESCRIPTION
**Pull request by paulo-ferraz-oliveira**
# Description

We were using a simple list of atoms to avoid to know if we should quote or not.

Not we're relying on Erlang/OTP's definition of atom (via a regex) and `erl_scan:f_reserved_word`, as discussed elsewhere, to know if we can actually unquote.

Closes #454.

- [x] I have read and understood the [contributing guidelines](/inaka/elvis_core/blob/main/CONTRIBUTING.md)

### CODE REVIEW

File: src/elvis_style.erl [hunk 1]
```diff
@@ -2733,7 +2733,7 @@ has_state_type(Root) ->
 spec_includes_record(Node) ->
     IsTypeRecord =
         fun(Child) ->
-            (ktn_code:type(Child) =:= 'type') andalso (ktn_code:attr(name, Child) =:= record)
+            (ktn_code:type(Child) =:= type) andalso (ktn_code:attr(name, Child) =:= record)
```
Comment (paulo-ferraz-oliveira) [inline src/elvis_style.erl:2736]: Finding stuff already 😄

**Review by bormilan — APPROVED** [review]

**Comment by paulo-ferraz-oliveira** [comment]
👍 

for me this is Ok, and since it's in a `strict` ruleset it'll be less "visible". Merging...
