### PR TITLE
`no_macros` now allows for `logger` default macros (`?LOG`, `?LOG_...` and friends)

### LINKED ISSUE #337: Should `no_macros` consider `LOG_...` as allowed?
## Bug Description

Maybe `no_macros` should consider `LOG_...` (and friends) as allowed (?)

## To Reproduce

Use `logger`'s `LOG_INFO`.

## Expected Behavior

No warnings.

## `rebar3` Logs

Not applicable.

## Additional Context

Not applicable.

### PR DESCRIPTION
**Pull request by kivra-pauoli**
Closes #337.

### CODE REVIEW

File: src/elvis_style.erl [hunk 1]
```diff
@@ -478,10 +478,12 @@ is_begin_node(Node) ->
     ktn_code:type(Node) =:= 'begin'.
 
 eep_predef_macros() ->
-    % From unexported eep:predef_macros/1
+    % From unexported epp:predef_macros/1
```
Comment (kivra-pauoli) [inline src/elvis_style.erl:481]: 😄

**Review by elbrujohalcon — APPROVED** [review]

**Comment by paulo-ferraz-oliveira** [comment]
Released, in Github, as 3.2.2.

**Comment by paulo-ferraz-oliveira** [comment]
Published, to Hex, as 3.2.2: https://hex.pm/packages/elvis_core/3.2.2
