### PR TITLE
Fix: Allow glob dir patterns that match nothing

### LINKED ISSUE #543: Default elvis config produces an error if the project is not an umbrellla one
## Bug Description

Using the config from `elvis_config:default()` on a minimal rebar3 project fails because there is no `apps/**/src` directory.

## To Reproduce

Run `elvis_core:rock(elvis_config:default()).` on a simple Erlang project, with folders such as `src`, `include`, etc… without an `apps` folder.

This error is reported:

```erlang
in 'elvis.config', at list position number 1, in 'dirs', the following elements are not (or don't contain) directories: ["apps/**/src"].
```

## Expected Behavior

Elvis runs with its default configuration.

## Additional Context

- OS: MacOS
- Erlang OTP28
- rebar3 26.0

### PR DESCRIPTION
**Pull request by NelsonVides**
Fixes #543

The dirs validation introduced in #515 rejected glob patterns like
`"apps/**/src"` when they didn't match any existing directories,
breaking non-umbrella projects using the default config.

Remove the per-element directory existence check entirely, and relax the
dir+filter combo validation to require that at least one combination
yields files, rather than all of them.

### CODE REVIEW

File: src/elvis_config.erl [hunk 1]
```diff
@@ -657,29 +656,6 @@ map_keys_are_in(Map, Keys) ->
                 ])}
     end.
 
-is_nonempty_list_of_dirs(What, List) when not is_list(List) orelse List =:= [] ->
-    {error, io_lib:format("'~s' is expected to be a non-empty list.", [What])};
```
Comment (kivra-pauoli) [inline src/elvis_config.erl]: Does this mean you no longer check for empty lists? Or where's the other (newer) check?

File: src/elvis_config.erl [hunk 2]
```diff
@@ -689,30 +665,15 @@ is_nonempty_string(What, String) ->
     end.
 
 all_dirs_filter_combos_are_valid(Dirs, Filter) ->
```
Comment (paulo-ferraz-oliveira) [inline src/elvis_config.erl]: I think this function is better named `at_least_one_dirs_filter_combo_is_valid`. I'll propose it.

File: src/elvis_config.erl (hunk 1 above)
Comment (NelsonVides) [reply src/elvis_config.erl]: The problem is that the default config contained both `apps/**/...` and `src/**` and chances are that almost for sure one of them is empty and then the default config would almost surely be invalid, which is a really bad practice. My change here was to ensure that at least one file can be found, so `dirs => []` would fail.

In any case, all of this is irrelevant now because we just reworked everything to stop using `dirs` so whatever, let's have this discussion in the current state :D
